apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
#   annotations:
#     rbac.authorization.kubernetes.io/autoupdate: "true"
#   labels:
#     kubernetes.io/bootstrapping: rbac-defaults
  name: console:built-in:view
rules:
- apiGroups:
  - ''
  resources:
  - pods
  verbs:
  - 'list'
  - 'get'
