apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: built-in:nodes:sa-proj-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: console:built-in:nodes
subjects:
- kind: ServiceAccount
  name: sa-proj-user
  namespace: console-users