apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: proj:admin:sa-proj-user
  namespace: console-users
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: console:proj:admin
subjects:
- kind: ServiceAccount
  name: sa-proj-user
  namespace: console-users