server:
  port: 8090

logging:
  level:
    org.apache.http: INFO

# https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html
management:
  endpoints:
    web:
      exposure:
        include: '*'