server:
  port: 8090

logging:
  level:
    org.apache.http: INFO
    com.example.rbac: DEBUG

# https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html
management:
  endpoints:
    web:
      exposure:
        include: '*'

# http://blog.egstep.com/spring-boot/2017/12/10/springboot-reload/
# https://stackoverflow.com/a/56005532
# https://dzone.com/articles/continuous-auto-restart-with-spring-boot-devtools
spring:
  devtools:
    restart:
      enabled: true
      exclude: ""
      # pollInterval: 3s
    livereload:
      enabled: true

# NOT WORKING
# https://github.com/syhily/spring-boot-retrofit-support
retrofit:
  connection:
  endpoints:
    grafana:
      baseUrl: http://grafana.local:8080/
      accessToken: xxxx
      logingLevel: DEBUG