apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-helm
  namespace: argo
spec:
  project: default
  source:
    repoURL: 'https://codecentric.github.io/helm-charts'
    chart: keycloak
    targetRevision: 6.2.0
    helm:
      values: |-
        keycloak:
          serviceAccount:
            create: true

          username: keycloak
          password: keycloak

          ingress:
            enabled: true
            hosts:
            - keycloak.local  # add to /etc/hosts

          persistence:
            deployPostgres: true
            dbVendor: postgres  # also mysql, mariadb
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: keycloak
