apiVersion: v1
kind: Pod
metadata:
  labels:
    app: kubectl
  name: kubectl
  namespace: console-users
spec:
  containers:
  - image: bitnami/kubectl
    imagePullPolicy: IfNotPresent
    name: kubectl
    command:
      - tail
      - -f
      - /dev/null
  securityContext:
    runAsUser: 0
  restartPolicy: Always
  serviceAccountName: sa-proj-user
  volumes:
  - emptyDir: {}
    name: tmp-dir